### ISSUE TITLE
"Connection Refused" on 3D45

### ISSUE THREAD

**Issue by eduncan911** [lwerner-lshigh/Dremel3D-CuraPrintr#1]
Hello and thanks for making this!  I've helped out a lot on the 3D20 plugin for many others.

I'm trying to use this right now with a 3D45; however, I am not sure what to put into the config for "URL".

Can I just enter the IP address?

When I enter the IP address in the format of an IP address, http://10.200.0.75 where .75 is the static IP for my printer, it says "Connection Refused."

I've confirmed that port 10123 is open and is accessible.

**Comment by timmehtimmeh** [comment]
@eduncan911 - as the creator of the 3D20 plugin let me first say thanks for the help you've given to any users of the 3D20 plugin - I sincerely appreciate it!  

I've recently gotten my hands on a 3D45, and saw this plugin and I had to test it.  I've also seen the "connection refused" error, and sometimes I've seen a "bad request" error and other times I've successfully sent a print to the 3D45.  FWIW here's what I put into the dialog box to connect to my 3D45:

![image](https://user-images.githubusercontent.com/19733103/125184149-3e52e800-e1d0-11eb-847d-b01406a73fa6.png)

It seems (at least based on the very little testing that I've done) that if I check the "Start Print Job" checkbox 
![image](https://user-images.githubusercontent.com/19733103/125184209-bde0b700-e1d0-11eb-8412-ad55642dc915.png)

then I get the "Bad request error" message, 
![image](https://user-images.githubusercontent.com/19733103/125184060-b5d44780-e1cf-11eb-829b-0bbdf2cf4635.png)

but if I leave that unchecked then the print uploads to the 3D45 and the printer starts printing:
![image](https://user-images.githubusercontent.com/19733103/125184128-211e1980-e1d0-11eb-85fd-5c418ccbe72f.png)



@lwerner-lshigh  - thank you for this plugin - I'm in the process of testing/releasing another plugin that will supersede the 3D20 plugin and allow users to add the 3D20/3D40 and 3D45 to Cura - between the two plugins this will open up a lot of possibilities for a lotof people! 

Cheers!

**Comment by eduncan911** [comment]
Welcome @timmehtimmeh !  Yeah, still using it for our 3d20.  Sorry I never got a Win7 install going with an older version of Dremel's software to debug.  That's awesome your plugin is coming along nicely with the 3d45!

Something to note for this issue: I recently updated the firmware of the 3d45 with the June 2021 update.

I can rarely, if ever, connect via browser to:

http://10.200.0.75:10123

Which, is how I used to monitor the webcam via a browser/on the TV.

I'm wondering if the June 2021 update had broken something within the 3d45 itself for remote connections.

**Comment by timmehtimmeh** [comment]
@eduncan911 - I got my 3D45 in late June, and immediately updated the firmware to the latest.  I've certainly seen instances where I can't get to the web page for my 3D45, but I blamed the quirks in my wifi network for those issues - I don't have enough history to know if older firmware was better or worse, but you may be onto something regarding the firmware breaking the networking or server in some way.  If you can't reach the server on your web brower then I'd bet that the dremel upload plugin also wouldn't be able to reach it.

One other thing to do is look through your [cura.log](https://support.ultimaker.com/hc/en-us/articles/360016538000-Saving-Ultimaker-Cura-logs) file for instances of `dremel3d_upload`...there are some places in this plugin's code that log info and error messages to that log file. i.e. 

```
2021-07-11 08:57:07,093 - DEBUG - [MainThread] dremel3d_upload.Dremel3DPlugin._checkDremel3DOutputDevices [33]: Dremel3D is active for printer: id:Dremel 3D45, name:Dremel 3D45
2021-07-11 08:57:07,093 - DEBUG - [MainThread] dremel3d_upload.Dremel3DOutputDevice.__init__ [70]: New Dremel3DOutputDevice 'dremel3d-upload' created | URL: http://192.168.1.24/ 
2021-07-11 08:57:07,109 - DEBUG - [MainThread] dremel3d_upload.Dremel3DOutputDevice._resetState [238]: Reset state
```

If I discover anything more then I'll post back here.

**Comment by eduncan911** [comment]
Something is vastly different now with the firmware update.  

Before, hitting the webpage worked 100% of the time, regardless of whatever state the printer was in.  The "webpage" was simply a webcam viewer of streaming jpg.  But now, it rarely, if ever, works.  It does connect sometimes, like 1 out of 10 times.

I have not narrowed down when it does or does not connect yet.

This is not normal at all.  And for historical sense, this isn't the first time Dremel has broken the 3D45 with a firmware update.  Last time it broke it took them 6 months to release another firmware.  (It last broke reading GCODE files, and you had to go back to 3drem files)

---

I knew I should not have upgraded...  Doh

**Comment by lukasmwerner** [comment]
Hello all 👋

Sorry I couldn't respond sooner, been in and out of cell service. 
So if I understand this thread correctly Dremel has released a new update for the 3D45 model which (may or may not) be leading to the http connection being dropped/refused. Unfortunately I do not have access to my school's 3D40 right now but as soon as I do I will look into this.

I would like to clarify some things about the Dremel architecture (based on my research on the 3D40).
The printer opens 3 ports and only port 80 is for API calls to the printer.

@eduncan911 The port in your issue is the mpeg stream of the camera.

Could one of you please try curl-ing the printers IP using the different API calls in the Research.md file?

**Comment by eduncan911** [comment]
Thanks for the response.  No rush.  :-)

Yes, the port I was mentioning was the camera/jpeg port.  It was used as reference that I can't seem to connect to the printer hardly ever after this firmware update.

Yep, tried port 80 for API reference - same thing.

For the record, I'm using a static IP and haven't ever had an issue connecting before this for ware update.

**Comment by lukasmwerner** [comment]
Once I get back to my desktop I will look into reversing the new firmware's network protocol. 
Do you know by any chance if there was a new version of digilab's slicer? 

It is quite odd that they would release a version that would remove features... Unfortunately I was unable to find a change log of the update.

**Comment by eduncan911** [comment]
Not sure of they changed the protocol.  It's the TCP connection that is sporatic, rarely ever connecting now.

**Comment by eduncan911** [comment]
Doh, it was me.  I had two devices on the same IP address (a RPi that I setup recently).  I haven't turned on the 3D45 in months.  I must not have written down the printer's IP as in use. Whoops.

Once I moved the static IP to a free one, I can connect to the printer.

Closing...

@timmehtimmeh maybe it is your wifi.  ;)

**Comment by timmehtimmeh** [comment]
>@timmehtimmeh maybe it is your wifi. ;)

I think it is.  I've only had issues connecting to the 3D45 a few times, and I intermittently have issues connecting to other rpi servers scattered around the house, but I haven't experienced anything like what you were reporting where only 1 out of 10 connection attempts were successful (I see maybe 1 out of 30 connection attempts fail).  

Anyway - I'm glad you solved it!
