### ISSUE TITLE
"Bad Request" when Uploading to 3D45

### ISSUE THREAD

**Issue by eduncan911** [lwerner-lshigh/Dremel3D-CuraPrintr#2]
As originally reported by @timmehtimmeh in #1 , there is an issue when selecting the "Start Print Job" checkbox when uploading.

Printer: 3D45
Firmware: June 2021

After slicing, and you click Upload to 3D45, you are prompted for a filename and to check a box for "Filename" and a checkbox for Start print job.

![image](https://user-images.githubusercontent.com/104980/125217278-3fe2e580-e28e-11eb-89f0-9d54db916843.png)

If you DO NOT check the box, the file is uploaded to the 3D45 and **it starts to print**.

If you DO check the box, the file is uploaded, and immediately an error message is shown:

![Screenshot from 2021-07-11 21-19-36](https://user-images.githubusercontent.com/104980/125217383-7d477300-e28e-11eb-94cc-8ff00dc94225.png)

And it does not start printing.

**Comment by lukasmwerner** [comment]
Thanks for creating a new issue for this bug. 
I finally am back to a computer so I'm gonna see whats going on with this bug.

**Comment by lukasmwerner** [comment]
Ok I think I've implemented a patch in [start-bug-patch](https://github.com/lwerner-lshigh/Dremel3D-CuraPrintr/tree/start-bug-patch). I found some old code from where I based this plugin off of. 

@eduncan911 Could you please try the patch in that branch? (Install via copying repo into plugin folder)

**Comment by timmehtimmeh** [comment]
@lwerner-lshigh  - I just tested your patch and it seems to fix the issue where checking the "automatically start" now does indeed automatically start the print job, whereas not checking the box brings up a progress bar that indicates that the print uploaded, however I'm not sure where to check to see that the print made its way to the 3d45.  ~When I don't check the "automatically start" checkbox there are no items in the print queue.   Is that where I should be looking?~

**Edit:** - after your updates if the user does not select the "automatically start" checkbox then the uploaded print appears on the USB stick, as long as the usb stick is inserted into the Dremel when the upload takes place.

From my (still very limited) testing it appears that the update works in all the testing that I've performed.  I'll let @eduncan911 respond if it works for him, but 👍 from me!

**Comment by lukasmwerner** [comment]
From my testing with the 3D40 the printer never saved the job. Granted I did not have a thumb drive in it. So thanks for that discovery @timmehtimmeh ! I am thinking about just getting rid of the dialogue box all together in order to just upload and start printing immediately.

**Comment by timmehtimmeh** [comment]
> I am thinking about just getting rid of the dialogue box all together in order to just upload and start printing immediately.

👍  I think that this would help avoid confusion and make the workflow super clear.

**Comment by lukasmwerner** [comment]
Closed & merged because of inactivity.
