### ISSUE TITLE
"name startUploading not defined"

### ISSUE THREAD

**Issue by JayBomb999** [lwerner-lshigh/Dremel3D-CuraPrintr#4]
First of all, thank you for your efforts on this.  I have been using this plugin for months without issue.  I just updated to version 1.02 and when "Start on Dremel3D45" is pressed, I receive the error message "name startUploading not defined".

![Capture](https://user-images.githubusercontent.com/91805237/135732360-6020d13e-710e-4cea-91c1-8a4a78112510.PNG)

**Comment by lukasmwerner** [comment]
Hi 👋 
Thanks for using this plugin! I also ran into this issue. Looks like I preemptively released the workflow improvements. Working on a fix now. Thank you for your patience.

**Comment by lukasmwerner** [comment]
Could you please try out the patch in [latest PR](https://github.com/lwerner-lshigh/Dremel3D-CuraPrintr/pull/5)

**Comment by JayBomb999** [comment]
Hello Lukas,

The latest update has fixed the problem.   Thank you very much for the
quick response.

Best regards,

Jason

**Comment by lukasmwerner** [comment]
Aright closing this because the latest merge fixes this issue. Will be uploading to the marketplace soon.

**Comment by JayBomb999** [comment]
Hello Lukas,

I'm a bit reluctant to ask, but I am curious if you had any plans to update
the Dremel wireless plug-in to work with Cura 5.0? I really appreciate your
plugin and use it nearly every week with Cura 4.xx.

Best regards,

Jason

**Comment by lukasmwerner** [comment]
I already have a issue (#6) open for that. I just submitted the plugin for ultimaker's approval process so should be in the 5.0 store in the coming days as long as they do not have any complaints

**Comment by JayBomb999** [comment]
I'm very glad to  hear that.  Thanks again for your work.  It is much
appreciated.

Regards,

Jason
